#!/bin/sh
#
# Start the Arcturus Programmin Station....
#

mkdir -p /Images

case "$1" in
  start|"")
	[ -f /APS/start_APS_imx6dlv.sh ] && echo "Starting APS: " || exit 1
	/bin/umount /Images
	/bin/umount /Images
	/bin/mount -t ext4 /dev/mmcblk0p3 /Images
	/APS/start_APS_imx6dlv.sh
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop) ;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
